version: '3.7'

services:
    nginx:
        image: nginx:latest
        container_name: "${PROJECT_NAME}_nginx"
        volumes:
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./:/var/www/
        ports:
            - "80:80"
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        container_name: "${PROJECT_NAME}_app"
        volumes:
            - ./:/var/www
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: "${PROJECT_NAME}_db"
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
             POSTGRES_PASSWORD: ${DB_PASSWORD}
             POSTGRES_USER: ${DB_USERNAME}
             POSTGRES_DB: ${DB_DATABASE}

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: "${PROJECT_NAME}_pgadmin"
        ports:
            - "5050:80"
        depends_on:
            - db
        environment:
              PGADMIN_DEFAULT_EMAIL: turist374@gmail.com
              PGADMIN_DEFAULT_PASSWORD: root

    redis:
        image: redis:latest
        container_name: "${PROJECT_NAME}_redis"
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
        depends_on:
            - app

    clickhouse:
        image: clickhouse/clickhouse-server
        container_name: "${PROJECT_NAME}_clickhouse"
        ports:
          - "8123:8123"
          - "9000:9000"
        volumes:
          - clickhouse:/var/lib/clickhouse
        depends_on:
          - app

    clickhouse-web:
        image: spoonest/clickhouse-tabix-web-client
        container_name: "${PROJECT_NAME}_clickhouse_web"
        restart: unless-stopped
        ports:
          - "3000:3000"
        depends_on:
          - clickhouse

volumes:
  db:
    name: ${PROJECT_NAME}_pgsql
  redis:
    name: ${PROJECT_NAME}_redis
  clickhouse:
    name: ${PROJECT_NAME}_clickhouse